/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Funcionalidad.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Robert
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    int dado;
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dado=4;
    }

    @Override
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/dado.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Duelo = new javax.swing.JButton();
        tirada = new javax.swing.JButton();
        Ver = new javax.swing.JButton();
        Offline = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        dado100 = new javax.swing.JButton();
        jugador = new javax.swing.JLabel();
        dado6 = new javax.swing.JButton();
        dado8 = new javax.swing.JButton();
        dado10 = new javax.swing.JButton();
        dado12 = new javax.swing.JButton();
        dado4 = new javax.swing.JButton();
        dado20 = new javax.swing.JButton();
        dado30 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        Duelo.setText("Duelo");
        Duelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DueloActionPerformed(evt);
            }
        });

        tirada.setText("Tirada Simple");
        tirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiradaActionPerformed(evt);
            }
        });

        Ver.setText("Ver Tirada");
        Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActionPerformed(evt);
            }
        });

        Offline.setText("Offline");
        Offline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfflineActionPerformed(evt);
            }
        });

        resultado.setBackground(new java.awt.Color(0, 0, 0));
        resultado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("Resultado");
        resultado.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255))));

        dado100.setText("100");
        dado100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado100ActionPerformed(evt);
            }
        });

        jugador.setBackground(new java.awt.Color(0, 0, 0));
        jugador.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jugador.setForeground(new java.awt.Color(255, 255, 255));
        jugador.setText("Jugador");
        jugador.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255))));

        dado6.setText("6");
        dado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado6ActionPerformed(evt);
            }
        });

        dado8.setText("8");
        dado8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado8ActionPerformed(evt);
            }
        });

        dado10.setText("10");
        dado10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado10ActionPerformed(evt);
            }
        });

        dado12.setText("12");
        dado12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado12ActionPerformed(evt);
            }
        });

        dado4.setText("4");
        dado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado4ActionPerformed(evt);
            }
        });

        dado20.setText("20");
        dado20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado20ActionPerformed(evt);
            }
        });

        dado30.setText("30");
        dado30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado30ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DADOS");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TIRADA");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dados-rol-gominola.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado4))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(tirada))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado30))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado100))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(Ver))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado20))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado12))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado10))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(Offline))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado6))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(dado8))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(Duelo))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(dado4)
                .addGap(67, 67, 67)
                .addComponent(tirada)
                .addGap(137, 137, 137)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(dado30))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(dado100))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(Ver))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(dado20))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(dado12))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(dado10))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(Offline))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(dado6))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(dado8))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Duelo))
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DueloActionPerformed
       
        Menu menu = new Menu();
        try {
            menu.iniciar(1,this.dado,this);
        } catch (InterruptedException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DueloActionPerformed

    private void dado100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado100ActionPerformed
        this.dado=100;
    }//GEN-LAST:event_dado100ActionPerformed

    private void dado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado4ActionPerformed
        this.dado=4;
    }//GEN-LAST:event_dado4ActionPerformed

    private void dado12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado12ActionPerformed
        this.dado=12;
    }//GEN-LAST:event_dado12ActionPerformed

    private void dado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado6ActionPerformed
       this.dado=6;
    }//GEN-LAST:event_dado6ActionPerformed

    private void dado8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado8ActionPerformed
        this.dado=8;
    }//GEN-LAST:event_dado8ActionPerformed

    private void dado10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado10ActionPerformed
       this.dado=10;
    }//GEN-LAST:event_dado10ActionPerformed

    private void dado20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado20ActionPerformed
       this.dado=20;
    }//GEN-LAST:event_dado20ActionPerformed

    private void dado30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado30ActionPerformed
        this.dado=30;
    }//GEN-LAST:event_dado30ActionPerformed

    private void tiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiradaActionPerformed
      Menu menu = new Menu();
        try {
            menu.iniciar(2,this.dado,this);
        } catch (InterruptedException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tiradaActionPerformed

    private void VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerActionPerformed
        Menu menu = new Menu();
        try {
            menu.iniciar(3,this.dado,this);
        } catch (InterruptedException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VerActionPerformed

    private void OfflineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfflineActionPerformed
        Menu menu = new Menu();
        try {
            menu.iniciar(4,this.dado,this);
        } catch (InterruptedException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OfflineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Duelo;
    private javax.swing.JButton Offline;
    private javax.swing.JButton Ver;
    private javax.swing.JButton dado10;
    private javax.swing.JButton dado100;
    private javax.swing.JButton dado12;
    private javax.swing.JButton dado20;
    private javax.swing.JButton dado30;
    private javax.swing.JButton dado4;
    private javax.swing.JButton dado6;
    private javax.swing.JButton dado8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jugador;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton tirada;
    // End of variables declaration//GEN-END:variables

  

    public void mostrarMiresultado(int y) {
        resultado.setText("Mi resultado es: "+y);
        System.out.print(y);
    }

    public void mostarJugador(String mensajeRecibido) {
       
        jugador.setText(mensajeRecibido);
        System.out.print(mensajeRecibido);
    }
}